name: "build"

on: ["pull_request", "push"]

jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v3.0.1
      - name : "Validate Gradle Wrapper"
        uses : "gradle/wrapper-validation-action@v1.0.4"
      - name : "Grab SHA"
        uses : "benjlevesque/short-sha@v1.2"
        id : "short-sha"
        with :
          length : "7"
      - name : "Echo SHA"
        run : "echo $SHA"
        env :
          SHA : "${{ steps.short-sha.outputs.sha }}"
      - name: "Setup JDK 16"
        uses: actions/setup-java@v3.0.0
        with:
          distribution: "temurin"
          java-version: "16"
      - name: Generate versions
        uses: HardNorth/github-version-generate@v1.1.1
        with:
          version-source: "file"
          version-file: "gradle.properties"
          version-file-extraction-pattern: "(?<=version=).+"
      - name: "Clean Build"
        run: "./gradlew clean build"
      - name : Archive Artifacts
        uses : actions/upload-artifact@v2
        with :
          name : Builders-Utilities-${{ env.CURRENT_VERSION }}-${{ env.SHA }}
          path : build/libs/Builders-Utilities-${{ env.CURRENT_VERSION }}-${{ env.SHA }}.jar
